version: "3"

services:
  app:
    build: 
      context: ./app             
    depends_on:                        
      - db    
    ports:
      - "8010:80"
      - "8011:443"
    volumes:
      - app_data:/var/lib/mysql
    #deploy:
    #  replicas: 3    #levanta 3 instancias. hay que ejecutar el docker-compose up --compatibility
  db:
    environment:
      - MYSQL_ROOT_PASSWORD:"${MYSQL_ROOT_PASSWORD}" 
    build: 
      context: ./db  
    restart: always
    ports:
      - "8020:3306"
      - "8021:8080"
    volumes:
      - db_data:/var/lib/mysql
    # lb:
    #   build: 
    #       context: ./lb                        #levanta el balanceador de carga
    #   ports:
    #     - "9000:80"
volumes:
  app_data:
  db_data: