version: "3"

services:
  jenkins:
    build: 
        context: ./jenkins             
    ports:
      - "8000:8080"                     
      - "8001:50000"  
    volumes:
        - jenkins_data:/var/jenkins_home     
  gitlab:
    build: 
        context: ./gitlab             
    ports:
      - "8002:22"                     
      - "8003:80"
      - "8004:443"      
    volumes:
        - gitlab_config:/etc/gitlab 
        - gitlab_logs:/var/log/gitlab
        - gitlab_data:/var/opt/gitlab
volumes:
    jenkins_data:
    gitlab_config:
    gitlab_logs:
    gitlab_data:
    
    