version: "3.7"
services:

    gitlab:
        build:
            context: .
            dockerfile: gitlab_dockerfile.yml
        #image: gitlab/gitlab-ce:latest
        #restart: always
        hostname: gitlab.pimpollo.ddns.net
        container_name: gitlab
        #environment:
        #    GITLAB_OMNIBUS_CONFIG: |    
        #        external_url 'https://gitlab.example.com'
        #        # Add any other gitlab.rb configuration here, each on its own line
        ports:
            - "9001:80"
            - "9000:443"
            - "9002:22"
        volumes:
            - gitlab_config:/etc/gitlab
            - gitlab_logs:/var/log/gitlab
            - gitlab_data:/var/opt/gitlab
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure

volumes:   
    gitlab_config:
        driver: local-persist
        driver_opts:
            mountpoint: $GITLAB_HOME/config
    gitlab_logs:
        driver: local-persist
        driver_opts:
            mountpoint: $GITLAB_HOME/logs
    gitlab_data:
        driver: local-persist
        driver_opts:
            mountpoint: $GITLAB_HOME/data