version: "3"

services:
  app:
    #image: platziapp
    build: 
        context: ./node                         #que me construya utilizando dentro del contexto actual la carpeta node (hace build segun el Dockerfile que encuentre)
    environment:                    
        MONGO_URL: "mongodb://db:27017/test"    #le envio a el docker platziapp una variable de entorno para que resuelva la cadena de conexion
    depends_on:                                 #para decir que este docker depende de db, pero no asegura que se ejecute correctamente antes
      - db
    ports:
      - "9001-9003:3000"                        #asigna un rango de puertos del servidor a los dockers (para escalar)
    volumes:
        - ./node:/usr/src                            #monta mi contexto de build en la carpeta src
        - /usr/src/node_modules                 #como hay archivos que no deben modificarse, le especificas el nombre para que no los toque
    deploy:
        replicas: 3                             #levanta 3 instancias. hay que ejecutar el docker-compose up --compatibility
  db:
     build: 
        context: ./mongo
  lb:
    build: 
        context: ./nginx                        #levanta el balanceador de carga
    ports:
      - "9000:80"